#
# CDA specific configuration information
#
[ConstrainedDevice]
deviceLocationID = constraineddevice001
enableSenseHAT = False
enableMqttClient = False
enableCoapServer = False
enableCoapClient = False
enableSystemPerformance = True
enableSensing = True
enableActuation = True
enableLogging = True
pollCycleSecs = 5
testGdaDataPath = /tmp/gda-data
testCdaDataPath = /tmp/cda-data
testEmptyApp = False
# Integration testing thresholds
nomHumidity = 30.0
nomTemperature = 20.0
nomPressure = 1013.25

humidFloor = 20.0
humidCeiling = 80.0
tempFloor = 0.0
tempCeiling = 30.0
pressureFloor = 900.0
pressureCeiling = 1100.0

# Enable emulator for testing
enableEmulator = False
enableSimulator = True

# configurable limits for sensor simulation
humiditySimFloor = 35.0
humiditySimCeiling = 45.0
pressureSimFloor = 990.0
pressureSimCeiling = 1010.0
tempSimFloor = 15.0
tempSimCeiling = 25.0

# configurable limits for actuator triggers
handleTempChangeOnDevice = True
triggerHvacTempFloor = 18.0
triggerHvacTempCeiling = 20.0

# camera settings
streamHostAddr = 127.0.0.1
streamHostLabel = localhost
streamPort = 8554
streamProtocol = rtsp
streamPath = stream
streamEncoding = MJPG
streamFrameWidth = 1440
streamFrameHeight = 1080
streamFps = 30
imageFileExt = .png
videoFileExt = .avi
minMotionPixelsDiff = 10000